import LegalPage from "../../components/LegalPage";

export const metadata = { title: "Política de Privacidade | Fluinow", description: "Como a Fluinow trata dados pessoais e atende aos direitos previstos na LGPD." };

export default function PrivacyPage() {
  return <LegalPage eyebrow="/ LGPD" title="Política de Privacidade">
    <p className="legal-lead">Esta política explica como a Fluinow trata dados pessoais no site <strong>fluinow.com.br</strong>, em contatos comerciais e na medição de campanhas, em conformidade com a Lei nº 13.709/2018 (LGPD).</p>
    <section><h2>1. Controlador e canal de privacidade</h2><p>O controlador é a <strong>Fluinow — Agência de IA e Marketing Digital</strong>, responsável pelas decisões sobre o tratamento realizado neste site. Para exercer direitos ou falar sobre privacidade, escreva para <a href="mailto:agfluinow@gmail.com">agfluinow@gmail.com</a>.</p></section>
    <section><h2>2. Dados tratados</h2><ul><li>dados enviados voluntariamente, como nome, e-mail, telefone, empresa e conteúdo da mensagem;</li><li>dados técnicos mínimos, como endereço IP, navegador, dispositivo, data, horário e registros de segurança;</li><li>dados de navegação e eventos de campanha, somente após consentimento para cookies opcionais;</li><li>informações fornecidas em conversas iniciadas pelo WhatsApp, e-mail ou outra plataforma escolhida pelo titular.</li></ul><p>Não solicitamos dados pessoais sensíveis por este site. Evite enviá-los em mensagens comerciais.</p></section>
    <section><h2>3. Finalidades e bases legais</h2><div className="legal-table"><div><strong>Finalidade</strong><strong>Base legal</strong></div><div><span>Responder contatos, elaborar propostas e prestar serviços</span><span>Procedimentos preliminares e execução de contrato</span></div><div><span>Segurança, prevenção a fraudes e funcionamento técnico</span><span>Legítimo interesse e obrigação legal</span></div><div><span>Medição de campanhas e publicidade personalizada</span><span>Consentimento, quando exigido</span></div><div><span>Deveres fiscais, regulatórios e defesa de direitos</span><span>Obrigação legal e exercício regular de direitos</span></div></div></section>
    <section><h2>4. Cookies e publicidade</h2><p>Cookies necessários podem preservar escolhas e manter o site seguro. Cookies de medição e marketing, incluindo tecnologias da Meta, só são ativados após autorização. É possível recusar sem perder acesso ao conteúdo e mudar a escolha em “Gerenciar cookies”. Consulte a <a href="/cookies">Política de Cookies</a>.</p></section>
    <section><h2>5. Compartilhamento</h2><p>Os dados podem ser compartilhados, no limite necessário, com fornecedores de hospedagem, segurança, comunicação, automação, análise e publicidade; assessorias profissionais; autoridades quando houver obrigação; e empresas envolvidas em reorganização societária. Ao acessar WhatsApp, Meta, Instagram ou outros serviços externos, aplicam-se também as políticas dessas plataformas.</p></section>
    <section><h2>6. Transferências internacionais</h2><p>Fornecedores tecnológicos podem processar dados fora do Brasil. Nesses casos, buscamos fornecedores com medidas contratuais, técnicas e organizacionais adequadas e mecanismos legais de transferência internacional aplicáveis.</p></section>
    <section><h2>7. Retenção</h2><p>Dados são mantidos apenas pelo tempo necessário às finalidades informadas. Registros contratuais, fiscais e de segurança podem ser conservados pelos prazos legais ou para exercício de direitos. Dados baseados em consentimento são eliminados ou anonimizados após revogação, salvo outra hipótese legal.</p></section>
    <section><h2>8. Direitos do titular</h2><p>Você pode pedir confirmação e acesso, correção, anonimização, bloqueio ou eliminação, portabilidade quando regulamentada, informações sobre compartilhamento, oposição, revisão de decisões automatizadas, revogação do consentimento e eliminação dos dados tratados com consentimento, observadas as exceções legais.</p><p>Envie gratuitamente sua solicitação para <a href="mailto:agfluinow@gmail.com?subject=Solicitação%20LGPD">agfluinow@gmail.com</a> com o assunto “Solicitação LGPD”. Poderemos solicitar informações estritamente necessárias para confirmar sua identidade.</p></section>
    <section><h2>9. Segurança e incidentes</h2><p>Adotamos controles técnicos e administrativos proporcionais aos riscos, incluindo restrição de acesso, autenticação, atualização de sistemas, backups e monitoramento. Incidentes relevantes serão avaliados e comunicados aos titulares e à ANPD quando exigido.</p></section>
    <section><h2>10. Crianças e adolescentes</h2><p>O site e nossos serviços comerciais não são direcionados a crianças. Caso identifiquemos tratamento indevido, adotaremos as medidas cabíveis considerando o melhor interesse do menor.</p></section>
    <section><h2>11. Atualizações</h2><p>Esta política pode mudar por razões legais, técnicas ou operacionais. Alterações relevantes serão informadas neste site e, quando necessário, será solicitado novo consentimento.</p></section>
  </LegalPage>;
}
